# Generated by Django 3.0.8 on 2020-09-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20200918_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='to_post',
        ),
    ]
