# Generated by Django 3.0.8 on 2020-09-20 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='post_text',
        ),
    ]
