# Generated by Django 3.0.8 on 2020-09-22 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200922_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='user_liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
